### ISSUE TITLE
Setup on windows

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qgis-pg-service-parser-plugin#26]
I tried to follow the docs on windows, creating a file at `%HOMEPATH%\.pg_service.conf` didn't work for me (it was not consumed by QGIS).
I had to set the `PGSERVICEFILE` env variable instead to make it work.

**Comment by 3nids** [comment]
for reference: https://www.postgresql.org/docs/current/libpq-pgservice.html

**Comment by m-kuhn** [comment]
```
os.path.expandvars('%APPDATA%')
'C:\\Users\\Matthias Kuhn\\AppData\\Roaming'
```

**Comment by gacarrillor** [comment]
Thanks for the report and sorry for the inconvenience.

The plugin's underlying lib reads the file by default at `~/.pg_service.conf` (not on `%APPDATA%\postgresql\.pg_service.conf` on Windows). So, the docs right now are describing only the plugin's behavior (which needs to be improved). 

I could have access to a Windows machine in the afternoon, I'll check it there directly and see whether we should add the `%APPDATA%\postgresql\.pg_service.conf` path as the only default location on Windows for the underlying lib. After all, it'd make much more sense if that's the only default location for QGIS on Windows.
