### ISSUE TITLE
Feature Request: Create new file

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qgis-pg-service-parser-plugin#27]
If no file exists, it would be great to automatically create one at the default location.

**Comment by 3nids** [comment]
should this feature be move to the lib? or we handle this in the plugin?

**Comment by gacarrillor** [comment]
Nice feature request.
If we create a new file, we'll need to be able to add/remove service setting items like `host` or `dbname`. I'll open another ticket for that.

We'd probably need to suggest a service setting template (i.e., with keys like host, user, and the like) ready to be filled. Non-required items might be removed by the user herself, which is much easier than letting her enter everything (i.e., keys and values).

**Comment by gacarrillor** [comment]
> should this feature be move to the lib? or we handle this in the plugin?

IMHO, this could be a plugin feature. In the GUI we'll do our best to assist users.

On the other hand, lib users will have Python available to create the file by themselves. For instance, by calling `conf_path()` they'll get the default PG service file location.

**Comment by m-kuhn** [comment]
A "open file in external editor" (even if not existing yet) would also work as a "make it easy to start from scratch" solution.

**Comment by gacarrillor** [comment]
> A "open file in external editor" (even if not existing yet) would also work as a "make it easy to start from scratch" solution.

I'd like to avoid that since we'd like them to use our plugin  :P.

**Comment by m-kuhn** [comment]
Nice would be that I can quickly get started without manually adding a template, or navigating through an explorer or even setting an env var

**Comment by gacarrillor** [comment]
The `host/port/dbname` was the 'template' I was talking about before.

![image](https://github.com/opengisch/qgis-pg-service-parser-plugin/assets/652785/9444505f-383c-460b-9c07-26e118451300)

**Comment by gacarrillor** [comment]
Fixed by #32
