### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by 3nids** [opengisch/qgis-pg-service-parser-plugin#5]
I've made some IA tests...one you like @gacarrillor ?

![image](https://github.com/opengisch/qgis-pg-service-parser-plugin/assets/127259/569eca83-9a5e-4f24-9093-b7a946646393)

![image](https://github.com/opengisch/qgis-pg-service-parser-plugin/assets/127259/e001f7b5-153f-4a79-ad96-8d0273b18481)

![image](https://github.com/opengisch/qgis-pg-service-parser-plugin/assets/127259/4d134bc1-b1bb-4338-8595-600f34001ac9)

![image](https://github.com/opengisch/qgis-pg-service-parser-plugin/assets/127259/07c265d9-f1f2-44d5-9747-29f35c2e81b2)

**Comment by gacarrillor** [comment]
I'd vote for the 3rd one :+1: 
My second place goes for the 4th one.
