### ISSUE TITLE
Issue with enumeration in QGIS 3.38

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/qgis-pg-service-parser-plugin#52]
![image](https://github.com/user-attachments/assets/1bde6768-5d04-4f3f-a80d-36deefd5b523)

Introduced in:

https://github.com/opengisch/qgis-pg-service-parser-plugin/pull/39/commits/1c713662e43887ed6ff319005eb22ab2371b886f#diff-d052f0c31410a31fcdfc6f028f399910abd0bc4c470f39eec8d1dc9a10e8b2dcR41

See: https://github.com/qgis/QGIS/commit/886074c913455ac4addf74e2aca3bf7098a7ad09

@3nids, how can we deal with this new enum value (it was `None_`, it's now `Standalone`) in a backwards-compatible way?

**Comment by 3nids** [comment]
Apparently it was `None` before https://github.com/qgis/QGIS/commit/886074c913455ac4addf74e2aca3bf7098a7ad09#diff-1131604372a226d4f27b61e9b47c94ed744f3f6f4bc7f656b6add5a14a2588a2L40

So I suppose it was not working at all.
Can you check for QGIS version and discard code if QGIS is not recent enough?
